import {addDocument,getSession,runQuery}from"./firebase-rest";
export type FeedbackRecord={id?:string;userId:string;appId:string;category:string;severity?:string|null;message:string;contact?:string|null;status:string;createdAt?:unknown};
export type IdeaStatus="New"|"Under Review"|"Selected for Development"|"In Development"|"Production"|"Revenue Generating"|"Not Selected";
export type IdeaRecord={id?:string;userId:string;contributorName?:string|null;title:string;problem?:string|null;audience?:string|null;details?:string|null;status:IdeaStatus;source:string;votes:number;grandfatheredAccess:boolean;creatorBonusEligible:boolean;creatorBonusStatus:"Not Eligible"|"Eligible"|"Approved"|"Paid";productionAppId?:string|null;rewardNote?:string|null;submissionTermsVersion:string;createdAt?:unknown};
function session(){const s=getSession();if(!s)throw new Error("Sign in with CactusByte ID™ first.");return s}
function uid(){return session().uid}
export async function submitFeedback(input:{appId:string;category:string;severity?:string;message:string;contact?:string}){return addDocument("feedback",{userId:uid(),appId:input.appId,category:input.category,severity:input.severity||null,message:input.message,contact:input.contact||null,status:"New"})}
export async function myFeedback():Promise<FeedbackRecord[]>{return runQuery("feedback","userId",uid(),"createdAt") as Promise<FeedbackRecord[]>}
export async function submitIdea(input:{title:string;problem?:string;audience?:string;details?:string;acceptedTerms:boolean}){const s=session();if(!input.acceptedTerms)throw new Error("Accept the IdeaForge™ submission terms before submitting.");return addDocument("ideas",{userId:s.uid,contributorName:s.email.split("@")[0],title:input.title,problem:input.problem||null,audience:input.audience||null,details:input.details||null,status:"New",source:"user",votes:1,grandfatheredAccess:false,creatorBonusEligible:false,creatorBonusStatus:"Not Eligible",productionAppId:null,rewardNote:null,submissionTermsVersion:"1.0"})}
export async function publicIdeas():Promise<IdeaRecord[]>{uid();return runQuery("ideas",undefined,undefined,"votes") as Promise<IdeaRecord[]>}
export const ideaRewardStages:IdeaStatus[]=["New","Under Review","Selected for Development","In Development","Production","Revenue Generating","Not Selected"];
export function rewardSummary(idea:IdeaRecord){if(idea.creatorBonusStatus==="Paid")return"Creator Bonus Paid";if(idea.creatorBonusEligible)return"Creator Bonus Eligible";if(idea.grandfatheredAccess)return"Lifetime Premium Access";if(idea.status==="Selected for Development"||idea.status==="In Development")return"Founding Contributor";return"Submitted"}
