import {createSign}from"crypto";
const PROJECT=process.env.FIREBASE_PROJECT_ID||"cactusbyte-studios";
const BASE=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents`;
let cached:{token:string;exp:number}|null=null;
const b64=(v:Buffer|string)=>Buffer.from(v).toString("base64url");
async function accessToken(){if(cached&&cached.exp>Date.now()+60000)return cached.token;const email=process.env.GOOGLE_CLIENT_EMAIL,key=(process.env.GOOGLE_PRIVATE_KEY||"").replace(/\\n/g,"\n");if(!email||!key)throw new Error("Firebase server credentials are not configured.");const now=Math.floor(Date.now()/1000),header=b64(JSON.stringify({alg:"RS256",typ:"JWT"})),claims=b64(JSON.stringify({iss:email,scope:"https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/cloud-platform",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,sign=createSign("RSA-SHA256");sign.update(unsigned);sign.end();const assertion=`${unsigned}.${sign.sign(key).toString("base64url")}`;const body=new URLSearchParams({grant_type:"urn:ietf:params:oauth2:grant-type:jwt-bearer",assertion});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body,cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error_description||"Unable to authorize Firebase server write.");cached={token:j.access_token,exp:Date.now()+(Number(j.expires_in||3600)*1000)};return cached.token}
const enc=(v:any):any=>v===null||v===undefined?{nullValue:null}:typeof v==="string"?{stringValue:v}:typeof v==="boolean"?{booleanValue:v}:typeof v==="number"?(Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v}):{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,enc(x)]))}};
const fields=(o:Record<string,any>)=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,enc(v)]));
export async function writeEntitlement(input:{userId:string;appId:string;status:string;stripeCustomerId?:string|null;stripeSubscriptionId?:string|null;stripePriceId?:string|null;sourceEvent?:string|null;currentPeriodEnd?:number|null;source?:string;plan?:string}){const id=encodeURIComponent(`${input.userId}_${input.appId}`),token=await accessToken();const data={userId:input.userId,appId:input.appId,plan:input.plan||"Pro",status:input.status,source:input.source||"Stripe",stripeCustomerId:input.stripeCustomerId||null,stripeSubscriptionId:input.stripeSubscriptionId||null,stripePriceId:input.stripePriceId||null,sourceEvent:input.sourceEvent||null,currentPeriodEnd:input.currentPeriodEnd||null,updatedAt:new Date().toISOString(),createdAt:new Date().toISOString()};const r=await fetch(`${BASE}/entitlements/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({fields:fields(data)}),cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Entitlement write failed.");return j}
