"use client";
import {useEffect,useMemo,useState}from"react";
import {studioApps,type StudioApp}from"../data/apps";
import {useCactusByteId}from"../lib/cactusbyte-id";
import {submitFeedback,submitIdea,myFeedback,publicIdeas,rewardSummary,type FeedbackRecord,type IdeaRecord}from"../lib/community-cloud";
import {defaultChannels,sendMessage,subscribeToMessages,type ChatMessage}from"../lib/chat-cloud";
import {enqueueByteLink,myByteLinkOutbox,destinationInbox,type StoredByteLinkMessage}from"../lib/bytelink-cloud";
import {createByteLinkEnvelope}from"../lib/bytelink";
const V="1.3.0";type Tab="apps"|"feedback"|"ideas"|"community"|"pulse"|"owner";type Sync={version:string;status:string;synced:boolean};
export default function Home(){const id=useCactusByteId();const[tab,setTab]=useState<Tab>("apps"),[sync,setSync]=useState<Record<string,Sync>>({}),[q,setQ]=useState(""),[note,setNote]=useState(""),[auth,setAuth]=useState(false),[compact,setCompact]=useState(false),[fb,setFb]=useState<FeedbackRecord[]>([]),[ideas,setIdeas]=useState<IdeaRecord[]>([]),[msgs,setMsgs]=useState<ChatMessage[]>([]),[channel,setChannel]=useState("general"),[out,setOut]=useState<StoredByteLinkMessage[]>([]),[inbox,setInbox]=useState<StoredByteLinkMessage[]>([]),[target,setTarget]=useState("cactusbyte-studios");
useEffect(()=>{if("serviceWorker"in navigator)void navigator.serviceWorker.getRegistrations().then(x=>Promise.all(x.map(r=>r.unregister())));void syncNow(false)},[]);
useEffect(()=>{if(!id.user){setFb([]);setIdeas([]);setOut([]);setInbox([]);return}void Promise.all([myFeedback().then(setFb),publicIdeas().then(setIdeas),myByteLinkOutbox().then(setOut),destinationInbox(target).then(setInbox)]).catch(()=>{})},[id.user,target]);
useEffect(()=>{if(!id.user){setMsgs([]);return}const u=subscribeToMessages(channel,setMsgs,e=>setNote(e.message));return()=>u()},[id.user,channel]);
async function syncNow(show=true){try{const r=await fetch("/api/registry",{cache:"no-store"});const p=await r.json();const n:Record<string,Sync>={};for(const x of p.apps??[])n[x.id]=x;setSync(n);if(show)setNote(`Registry synced: ${Object.values(n).filter(x=>x.synced).length}/${studioApps.length}`)}catch{if(show)setNote("Registry unavailable. Known LIVE links preserved.")}}
const apps=useMemo(()=>studioApps.filter(a=>!q||`${a.name} ${a.category}`.toLowerCase().includes(q.toLowerCase())),[q]);const ver=(a:StudioApp)=>sync[a.id]?.version??a.version;const stat=(a:StudioApp)=>sync[a.id]?.status??a.status;
return <main className="shell"><header><div><b>Cactus🌵Byte Studios™</b><small>Command Center · v{V}</small></div><div><button onClick={()=>setCompact(!compact)}>My CactusByte</button><button onClick={()=>setAuth(!auth)}>{id.user?"CactusByte ID":"Sign In"}</button></div></header><section className="hero"><h1>Connected CactusByte.</h1><p>Apps, identity, feedback, ideas, community and ByteLink™ in one ecosystem.</p></section>{auth&&<Auth id={id}/>}<section className="identity"><b>{id.user?(id.profile?.displayName||id.user.email):"Not signed in"}</b><span>{id.user?`Role: ${id.profile?.role||"user"}`:"Cloud features require CactusByte ID™"}</span></section>{note&&<div className="notice">{note}<button onClick={()=>setNote("")}>×</button></div>}<nav>{(["apps","feedback","ideas","community","pulse","owner"]as Tab[]).map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section className="infra"><State n="Registry" s="Connected"/><State n="Firebase" s="Connected"/><State n="ByteLink™" s="Development"/></section>
{tab==="apps"&&<><div className="head"><h2>Studio Registry</h2><button onClick={()=>void syncNow()}>Sync Registry</button></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search apps"/><div className={`grid ${compact?"compact":""}`}>{apps.map(a=><article className="card" key={a.id}><div className="cardtop"><img src={a.logo} alt={`${a.shortName} logo`}/><span className={stat(a)==="Live"?"live":"dev"}>{stat(a)}</span></div><small>{a.category}</small><h3>{a.name}</h3><p>{a.description}</p><div className="meta"><span>{a.platform}</span><span>{ver(a)}</span></div>{a.monetization&&<div className="price">{a.monetization.free}<b>{a.monetization.proPrice}</b></div>}<div className="actions">{a.url?<a href={a.url} target="_blank">Open App</a>:<button disabled>Link Pending</button>}<button onClick={()=>navigator.share?navigator.share({title:a.name,url:a.url??a.repo}):navigator.clipboard.writeText(a.url??a.repo)}>Share</button></div></article>)}</div></>}
{tab==="feedback"&&<Feedback signed={!!id.user} rows={fb} need={()=>setAuth(true)} done={async x=>{await submitFeedback(x);setFb(await myFeedback());setNote("Feedback saved to CactusByte Cloud.")}}/>}
{tab==="ideas"&&<Ideas signed={!!id.user} rows={ideas} need={()=>setAuth(true)} done={async x=>{await submitIdea(x);setIdeas(await publicIdeas());setNote("Idea saved to Idea Forge™ with contributor attribution.")}}/>}
{tab==="community"&&<Community signed={!!id.user} rows={msgs} channel={channel} setChannel={setChannel} need={()=>setAuth(true)} send={async t=>sendMessage({channelId:channel,displayName:id.profile?.displayName||id.user?.email||"CactusByte User",body:t})}/>} 
{tab==="pulse"&&<Pulse signed={!!id.user} out={out} inbox={inbox} target={target} setTarget={setTarget} need={()=>setAuth(true)} send={async(d,t)=>{await enqueueByteLink(createByteLinkEnvelope({sourceApp:"cactusbyte-studios",destinationApp:d,contentType:"text.note",permissions:["user:send"],payload:{text:t}}));setOut(await myByteLinkOutbox());setInbox(await destinationInbox(target));setNote("ByteLink message queued.")}}/>}
{tab==="owner"&&<Owner signed={!!id.user} owner={id.profile?.role==="owner"} fb={fb.length} ideas={ideas} need={()=>setAuth(true)}/>}<section className="support"><h2>Fuel the Next Update™</h2><p>Support stays optional so the command center remains free.</p><button disabled>$5</button><button disabled>$10</button><span>Stripe one-time support: Development</span></section><section className="panel"><b>CactusByte Help &amp; Legal</b><p><a href="/support">Support</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms &amp; Idea Forge™ Contributor Terms</a></p></section><footer>Cactus🌵Byte Studios™ v{V} · Cactus🌵Byte Studios™ · All Rights Reserved</footer></main>}
function State({n,s}:{n:string;s:string}){return <div><i className={s==="Connected"?"green":"amber"}/><b>{n}</b><span>{s}</span></div>}
function Gate({go,text}:{go:()=>void;text:string}){return <section className="panel"><p>{text}</p><button onClick={go}>Sign In</button></section>}
function Auth({id}:{id:ReturnType<typeof useCactusByteId>}){const[e,setE]=useState(""),[p,setP]=useState(""),[err,setErr]=useState("");if(id.user)return <section className="panel"><b>{id.user.email}</b><p>Role: {id.profile?.role||"user"}</p><button onClick={()=>void id.logout()}>Sign Out</button></section>;return <section className="panel form"><input value={e} onChange={x=>setE(x.target.value)} placeholder="Email"/><input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="Password"/>{err&&<p>{err}</p>}<button onClick={()=>void id.login(e,p).catch(x=>setErr(x.message))}>Sign In</button><button onClick={()=>void id.register(e,p).catch(x=>setErr(x.message))}>Create Account</button><button onClick={()=>void id.loginWithGoogle().catch(x=>setErr(x.message))}>Continue with Google</button></section>}
function Feedback({signed,rows,need,done}:{signed:boolean;rows:FeedbackRecord[];need:()=>void;done:(x:{appId:string;category:string;message:string})=>Promise<void>}){const[m,setM]=useState("");if(!signed)return <Gate go={need} text="Sign in to submit persistent feedback."/>;return <section className="panel"><h2>Feedback Hub™</h2><textarea value={m} onChange={e=>setM(e.target.value)} placeholder="Bug, request or improvement"/><button onClick={()=>void done({appId:"cactusbyte-studios",category:"Feedback",message:m}).then(()=>setM(""))}>Submit</button>{rows.map(x=><div className="row" key={x.id}><b>{x.category}</b><p>{x.message}</p></div>)}</section>}
function Ideas({signed,rows,need,done}:{signed:boolean;rows:IdeaRecord[];need:()=>void;done:(x:{title:string;problem?:string;audience?:string;details?:string;acceptedTerms:boolean})=>Promise<void>}){const[t,setT]=useState(""),[p,setP]=useState(""),[a,setA]=useState(""),[d,setD]=useState(""),[ok,setOk]=useState(false);if(!signed)return <Gate go={need} text="Sign in to submit persistent app ideas."/>;return <section className="panel form"><h2>Idea Forge™</h2><p>Submit an original app idea and track it from review through production. Ideas selected for development can earn Founding Contributor recognition and lifetime premium access. Revenue-generating ideas may become eligible for a Creator Bonus.</p><input value={t} onChange={e=>setT(e.target.value)} placeholder="App idea / name"/><textarea value={p} onChange={e=>setP(e.target.value)} placeholder="Problem it solves"/><input value={a} onChange={e=>setA(e.target.value)} placeholder="Who it helps"/><textarea value={d} onChange={e=>setD(e.target.value)} placeholder="Additional details"/><label><input type="checkbox" checked={ok} onChange={e=>setOk(e.target.checked)}/> I agree to the <a href="/terms">Idea Forge™ Contributor Terms</a>. Submission does not automatically create ownership, royalties, employment, partnership, or a guaranteed reward. Similar ideas may already exist or be under development.</label><button disabled={!ok||!t.trim()} onClick={()=>void done({title:t,problem:p,audience:a,details:d,acceptedTerms:ok}).then(()=>{setT("");setP("");setA("");setD("");setOk(false)})}>Submit Idea</button>{rows.map(x=><div className="row" key={x.id}><b>{x.title}</b><p>{x.problem}</p><span>{x.status} · {rewardSummary(x)} · {x.votes} vote{x.votes===1?"":"s"}</span>{x.contributorName&&<small>Original Contributor: {x.contributorName}</small>}</div>)}</section>}
function Community({signed,rows,channel,setChannel,need,send}:{signed:boolean;rows:ChatMessage[];channel:string;setChannel:(x:string)=>void;need:()=>void;send:(x:string)=>Promise<unknown>}){const[t,setT]=useState("");if(!signed)return <Gate go={need} text="Sign in to join Community Chat™."/>;return <section className="panel"><h2>Community Chat™</h2><div className="channels">{defaultChannels.map(c=><button className={c.id===channel?"on":""} onClick={()=>setChannel(c.id)} key={c.id}>{c.label}</button>)}</div><div className="chat">{rows.map(x=><div key={x.id}><b>{x.displayName}</b><p>{x.body}</p></div>)}</div><div className="compose"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Message"/><button onClick={()=>void send(t).then(()=>setT(""))}>Send</button></div></section>}
function Pulse({signed,out,inbox,target,setTarget,need,send}:{signed:boolean;out:StoredByteLinkMessage[];inbox:StoredByteLinkMessage[];target:string;setTarget:(x:string)=>void;need:()=>void;send:(d:string,t:string)=>Promise<void>}){const[d,setD]=useState("fantasy-matrix"),[t,setT]=useState("");if(!signed)return <Gate go={need} text="Sign in to test ByteLink™."/>;return <section className="panel form"><h2>ByteLink™ Transport</h2><p>Development: persistent queue is live; cryptographic app identities are not yet enabled.</p><select value={d} onChange={e=>setD(e.target.value)}>{studioApps.map(a=><option value={a.id} key={a.id}>{a.shortName}</option>)}</select><textarea value={t} onChange={e=>setT(e.target.value)} placeholder="Test payload"/><button onClick={()=>void send(d,t).then(()=>setT(""))}>Queue Message</button><select value={target} onChange={e=>setTarget(e.target.value)}><option value="cactusbyte-studios">CactusByte Studios</option>{studioApps.map(a=><option value={a.id} key={a.id}>{a.shortName}</option>)}</select><div className="row">Outbox: {out.length} · Destination inbox: {inbox.length}</div></section>}
function Owner({signed,owner,fb,ideas,need}:{signed:boolean;owner:boolean;fb:number;ideas:IdeaRecord[];need:()=>void}){if(!signed)return <Gate go={need} text="Sign in with the owner CactusByte ID™."/>;if(!owner)return <section className="panel"><h2>Owner Console™</h2><p>Access denied. Firestore role is not owner.</p></section>;return <section className="panel"><h2>Owner Console™</h2><p>Authenticated by Firebase + Firestore owner role.</p><div className="stats"><b>{studioApps.length}<span>Apps</span></b><b>{fb}<span>My feedback</span></b><b>{ideas.length}<span>Ideas</span></b></div><h3>IdeaForge™ Contributor Rewards</h3><p>Only owner/moderator roles can approve development status, lifetime access, Creator Bonus eligibility, or payment status.</p>{ideas.map(x=><div className="row" key={x.id}><b>{x.title}</b><p>{x.contributorName||x.userId}</p><span>{x.status} · {rewardSummary(x)}</span></div>)}</section>}
