import {NextRequest,NextResponse}from"next/server";
import {STRIPE_PRICE_TO_APP,stripeGet,verifyStripeSignature}from"../../../../lib/stripe-billing-server";
import {writeEntitlement}from"../../../../lib/firestore-admin-rest";
export const dynamic="force-dynamic";
function meta(obj:any){return obj?.metadata||{}}
function priceFromSubscription(sub:any){return sub?.items?.data?.[0]?.price?.id||null}
function appFrom(sub:any,priceId?:string|null){return meta(sub).cactusbyte_app_id||meta(sub).appId||(priceId?STRIPE_PRICE_TO_APP[priceId]:null)||null}
function userFrom(sub:any){return meta(sub).cactusbyte_user_id||meta(sub).userId||null}
async function persistSubscription(sub:any,eventType:string,statusOverride?:string){const priceId=priceFromSubscription(sub),appId=appFrom(sub,priceId),userId=userFrom(sub);if(!appId||!userId)return;const raw=String(statusOverride||sub.status||"active").toLowerCase();const status=["active","trialing"].includes(raw)?"active":["past_due","unpaid","incomplete","incomplete_expired"].includes(raw)?"suspended":["canceled","cancelled"].includes(raw)?"canceled":raw;await writeEntitlement({userId,appId,status,stripeCustomerId:typeof sub.customer==="string"?sub.customer:sub.customer?.id||null,stripeSubscriptionId:sub.id||null,stripePriceId:priceId,sourceEvent:eventType,currentPeriodEnd:sub.current_period_end||null})}
export async function POST(req:NextRequest){const payload=await req.text(),sig=req.headers.get("stripe-signature")||"";try{if(!verifyStripeSignature(payload,sig))return NextResponse.json({error:"Invalid Stripe signature."},{status:400});const event=JSON.parse(payload),obj=event?.data?.object;switch(event.type){case"checkout.session.completed":{if(obj?.mode!=="subscription")break;const subId=typeof obj.subscription==="string"?obj.subscription:obj.subscription?.id;if(!subId)break;const sub=await stripeGet(`subscriptions/${subId}?expand[]=items.data.price`);await persistSubscription(sub,event.type);break}case"customer.subscription.created":case"customer.subscription.updated":case"customer.subscription.deleted":await persistSubscription(obj,event.type,event.type.endsWith("deleted")?"canceled":undefined);break;case"invoice.payment_failed":{const subId=typeof obj?.subscription==="string"?obj.subscription:obj?.subscription?.id;if(subId){const sub=await stripeGet(`subscriptions/${subId}?expand[]=items.data.price`);await persistSubscription(sub,event.type,"suspended")}break}case"invoice.paid":{const subId=typeof obj?.subscription==="string"?obj.subscription:obj?.subscription?.id;if(subId){const sub=await stripeGet(`subscriptions/${subId}?expand[]=items.data.price`);await persistSubscription(sub,event.type,"active")}break}}return NextResponse.json({received:true})}catch(e){console.error("Stripe webhook error",e);return NextResponse.json({error:e instanceof Error?e.message:"Webhook processing failed."},{status:500})}}
