import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const exists=p=>fs.existsSync(path.join(root,p));
const fail=[];
const pass=[];
const check=(ok,msg)=>{(ok?pass:fail).push(msg)};

const ownerDevice=exists("src/lib/owner-device.ts")?read("src/lib/owner-device.ts"):"";
const ownerAccess=exists("src/lib/owner-access.ts")?read("src/lib/owner-access.ts"):"";
const ownerSession=exists("src/app/api/owner/session/route.ts")?read("src/app/api/owner/session/route.ts"):"";
const ownerStats=exists("src/app/api/owner/stats/route.ts")?read("src/app/api/owner/stats/route.ts"):"";
const authTrack=exists("src/app/api/auth/track/route.ts")?read("src/app/api/auth/track/route.ts"):"";
const portal=exists("src/app/api/stripe/portal/route.ts")?read("src/app/api/stripe/portal/route.ts"):"";
const testerPass=exists("src/lib/tester-pass.ts")?read("src/lib/tester-pass.ts"):"";
const testerRedeem=exists("src/app/api/tester/redeem/route.ts")?read("src/app/api/tester/redeem/route.ts"):"";
const testerStatus=exists("src/app/api/tester/status/route.ts")?read("src/app/api/tester/status/route.ts"):"";
const cactusId=read("src/lib/cactusbyte-id.ts");
const firebaseRest=read("src/lib/firebase-rest.ts");
const dock=exists("src/app/account-dock.tsx")?read("src/app/account-dock.tsx"):"";
const brandedShare=exists("src/app/branded-share.tsx")?read("src/app/branded-share.tsx"):"";
const authSurface=exists("src/app/cactusbyte-auth-surface.tsx")?read("src/app/cactusbyte-auth-surface.tsx"):"";
const layout=read("src/app/layout.tsx");
const mobile=exists("src/app/mobile.css")?read("src/app/mobile.css"):"";
const rules=read("firestore.rules");
const env=read(".env.example");

check(Boolean(ownerDevice),"Trusted owner-device helper exists");
check(ownerDevice.includes("HttpOnly")&&ownerDevice.includes("SameSite=Strict"),"Trusted owner credential is stored in an HttpOnly SameSite=Strict cookie");
check(ownerDevice.includes("OWNER_DEVICE_SIGNING_SECRET"),"Owner-device token is signed with a server-only secret");
check(ownerAccess.includes('role!=="owner"'),"Normal CactusByte ID owner access still checks the Firestore owner role");
check(ownerSession.includes("createCustomToken"),"Trusted owner device can obtain a Firebase custom token without password login");
check(firebaseRest.includes("accounts:signInWithCustomToken"),"Firebase REST client supports silent owner custom-token sign-in");
check(cactusId.includes("ownerAutoSession"),"CactusByte ID attempts silent trusted-owner restoration on startup");
check(cactusId.includes("hasOwnerBackup()")&&cactusId.includes('isOwner:ownerSessionActive||hasOwnerBackup()||profile?.role==="owner"'),"Trusted owner backup remains authoritative for owner UI");
check(cactusId.includes('return ownerSessionActive||hasOwnerBackup()?asOwner(p):p'),"Trusted owner backup upgrades the loaded profile to owner before rendering");
check(cactusId.includes('/api/auth/track'),"CactusByte ID records login/register events through the server tracker");
check(Boolean(authTrack)&&authTrack.includes("verifyIdToken"),"Auth-event tracking verifies Firebase identity server-side");
check(rules.includes("match /authEvents/{id}")&&rules.includes("allow read, write: if false"),"Raw auth-event documents are blocked from client Firestore access");
check(Boolean(ownerStats)&&ownerStats.includes("listUsers"),"Owner analytics derives the registered-user count from Firebase Auth");
check(ownerStats.includes("isUserAuth")&&ownerStats.includes("ownerRestores24h"),"Owner restores are separated from real user sign-in counts");
check(Boolean(portal)&&portal.includes("billingPortal.sessions.create"),"Stripe customer portal session route exists");
check(portal.includes("subscription_cancel")&&portal.includes("payment_method_update"),"Stripe portal enables cancel-at-period-end and payment-method management");
check(Boolean(dock)&&dock.includes("Manage Billing")&&dock.includes("Owner Stats"),"Account dock exposes subscription management and owner-only analytics controls");
check(layout.includes("<AccountDock/>")&&layout.includes('import "./mobile.css"'),"Account dock and phone stylesheet are mounted globally");
check(mobile.includes("max-device-width:500px")&&mobile.includes(".grid{grid-template-columns:1fr!important}")&&mobile.includes(".grid.list{grid-template-columns:1fr!important}"),"Phone stylesheet forces a readable one-column app grid even in wide mobile/custom-tab viewports");
check(Boolean(brandedShare)&&brandedShare.includes("CACTUSBYTE SHARE™")&&brandedShare.includes("Android / iOS Share"),"CactusByte branded QR share surface exists");
check(layout.includes("<BrandedShare/>"),"CactusByte branded share surface is mounted globally");
check(Boolean(authSurface)&&authSurface.includes("Your email address is your CactusByte ID")&&authSurface.includes("Create a password")&&authSurface.includes("Forgot password?")&&authSurface.includes("Show password"),"CactusByte ID clearly explains email login, account creation and password visibility");
check(firebaseRest.includes('accounts:sendOobCode')&&firebaseRest.includes('PASSWORD_RESET'),"Firebase password-reset email flow is implemented");
check(layout.includes("<CactusByteAuthSurface/>"),"CactusByte ID account surface is mounted globally");
check(authSurface.includes("Continue browsing without an account"),"CactusByte remains browseable without a forced sign-in wall");
check((testerPass.match(/[a-f0-9]{64}/g)||[]).length===8&&testerPass.includes("timingSafeEqual"),"Exactly eight tester coupon hashes are staged and verified without storing raw coupon codes");
check(testerPass.includes("verifyIdToken")&&testerRedeem.includes("testerIdentity(request)"),"Tester coupon redemption is bound to a verified CactusByte ID");
check(testerRedeem.includes('collection("testerCoupons")')&&testerRedeem.includes("COUPON_ALREADY_REDEEMED"),"Tester coupons are single-use and account-bound");
check(testerRedeem.includes('plan:"tester-lifetime"')&&testerRedeem.includes('source:"tester_coupon"')&&testerRedeem.includes('status:"lifetime"')&&testerRedeem.includes("expiresAt:null"),"Tester coupons grant non-expiring tester entitlements without a Stripe subscription");
check(testerRedeem.includes('role:"tester"')&&!testerRedeem.toLowerCase().includes("stripe"),"Tester redemption assigns tester role without creating Pro billing status");
check(Boolean(testerStatus)&&authSurface.includes("/api/tester/status")&&authSurface.includes("/api/tester/redeem")&&authSurface.includes("TESTER LIFETIME PASS"),"CactusByte ID exposes tester-pass status and redemption UI");
check(authSurface.includes("VIP STATUS UNLOCKED™")&&authSurface.includes("LIFETIME VIP ACTIVATED")&&authSurface.includes("Enter Cactus🌵Byte")&&authSurface.includes("View My VIP Access"),"Tester redemption launches the cinematic lifetime VIP success experience");
check(authSurface.includes("cbVipSweep")&&authSurface.includes("cbVipRing")&&authSurface.includes("cbVipParticle")&&authSurface.includes("prefers-reduced-motion"),"VIP success animation includes energy sweep, radar rings, particles and reduced-motion accessibility");
check(authSurface.includes("VIP Tester · Lifetime")&&authSurface.includes("cactusbyte:tester-redeemed"),"Lifetime VIP state is visible in the account surface and emits a refresh event after redemption");
check(exists("src/app/owner-device/page.tsx"),"One-time owner device setup page exists");
check(env.includes("OWNER_DEVICE_SETUP_SECRET")&&env.includes("OWNER_DEVICE_SIGNING_SECRET"),"Owner-device production secrets are documented");
check(!/NEXT_PUBLIC_OWNER|NEXT_PUBLIC_STRIPE_SECRET|NEXT_PUBLIC_FIREBASE_ADMIN/.test(env+ownerDevice+ownerAccess+portal),"Owner, Stripe secret and Firebase Admin credentials are never exposed as NEXT_PUBLIC variables");

console.log("\nCactusByte owner + billing preflight");
for(const x of pass)console.log(`✓ ${x}`);
for(const x of fail)console.error(`✗ ${x}`);
console.log(`\n${pass.length} passed · ${fail.length} failed`);
if(fail.length)process.exit(1);