"use client";

import {useEffect,useState} from "react";
import {getFreshSession} from "../../lib/firebase-rest";

type Installation={appId:string;installationId:string;deviceLabel:string;active:boolean;createdAtMs:number;updatedAtMs:number;lastSeenAtMs:number;lastRestoredAtMs:number;revokedAtMs:number};
const appName=(appId:string)=>appId==="orbitgather"?"OrbitGather™":appId;
const when=(ms:number)=>ms?new Date(ms).toLocaleString():"Not recorded";

export default function LinkedDevicesPage(){
 const[rows,setRows]=useState<Installation[]>([]),[busy,setBusy]=useState(true),[note,setNote]=useState(""),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const session=await getFreshSession();if(!session)throw new Error("Sign in with CactusByte ID™ from the hub first.");const r=await fetch("/api/identity/installations",{headers:{Authorization:`Bearer ${session.idToken}`},cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(j?.error||"Linked devices could not be loaded."));setRows(Array.isArray(j?.installations)?j.installations:[])}catch(e){setError(e instanceof Error?e.message:"Linked devices could not be loaded.")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 async function revoke(row:Installation){if(!row.active)return;const confirmed=window.confirm(`Revoke the CactusByte recovery link for ${appName(row.appId)} on ${row.deviceLabel}? This does not delete app data, but this installation cannot be restored through CactusByte ID until it is protected again.`);if(!confirmed)return;setBusy(true);setError("");setNote("");try{const session=await getFreshSession();if(!session)throw new Error("Sign in with CactusByte ID™ first.");const r=await fetch("/api/identity/installations",{method:"DELETE",headers:{Authorization:`Bearer ${session.idToken}`,"Content-Type":"application/json"},body:JSON.stringify({appId:row.appId,installationId:row.installationId}),cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(j?.error||"Recovery link could not be revoked."));setNote("Recovery link revoked. The app's cloud data was not deleted.");await load()}catch(e){setError(e instanceof Error?e.message:"Recovery link could not be revoked.");setBusy(false)}}
 return <main style={{minHeight:"100dvh",background:"#040907",color:"#f4fffc",padding:"24px 14px",fontFamily:"system-ui,-apple-system,sans-serif"}}><section style={{width:"min(840px,100%)",margin:"0 auto"}}><button onClick={()=>location.assign("/")} style={secondary}>← CactusByte Hub</button><div style={{margin:"18px 0"}}><span style={{fontSize:11,fontWeight:900,letterSpacing:".15em",color:"#00d5be"}}>CACTUSBYTE ID™</span><h1 style={{fontSize:"clamp(2rem,8vw,3.2rem)",margin:"8px 0"}}>Linked Devices</h1><p style={{color:"#a6bbb5",lineHeight:1.6,maxWidth:700}}>These are installation identities protected by your CactusByte ID. Revoking a link removes recovery authority only; it does not delete the app, billing, or cloud records.</p></div>{busy&&!rows.length&&<p>Loading linked devices…</p>}{error&&<p role="alert" style={{color:"#ffaaa9",fontWeight:750}}>{error}</p>}{note&&<p role="status" style={{color:"#8fffd4",fontWeight:750}}>{note}</p>}
  <div style={{display:"grid",gap:12}}>{rows.length?rows.map(row=><article key={`${row.appId}-${row.installationId}`} style={{border:"1px solid rgba(0,213,190,.18)",borderRadius:18,padding:16,background:"rgba(255,255,255,.025)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><b style={{fontSize:19}}>{appName(row.appId)}</b><div style={{marginTop:4,color:row.active?"#8fffd4":"#ffb2b2",fontWeight:800}}>{row.active?"Active recovery link":"Revoked"}</div></div>{row.active&&<button disabled={busy} onClick={()=>void revoke(row)} style={danger}>Revoke recovery link</button>}</div><dl style={{display:"grid",gridTemplateColumns:"minmax(110px,auto) 1fr",gap:"7px 12px",margin:"14px 0 0",fontSize:14}}><dt style={dt}>Device</dt><dd style={dd}>{row.deviceLabel}</dd><dt style={dt}>Installation UUID</dt><dd style={{...dd,fontFamily:"ui-monospace,SFMono-Regular,monospace",overflowWrap:"anywhere"}}>{row.installationId}</dd><dt style={dt}>Last seen</dt><dd style={dd}>{when(row.lastSeenAtMs||row.updatedAtMs)}</dd><dt style={dt}>Last restored</dt><dd style={dd}>{when(row.lastRestoredAtMs)}</dd></dl></article>):!busy&&!error?<div style={{padding:18,border:"1px dashed rgba(255,255,255,.18)",borderRadius:16,color:"#9eb0aa"}}>No protected installations are linked to this CactusByte ID yet.</div>:null}</div>
 </section></main>;
}
const secondary={minHeight:44,border:"1px solid rgba(0,213,190,.24)",borderRadius:12,background:"rgba(0,213,190,.06)",color:"#eafffa",padding:"0 14px",fontWeight:800,cursor:"pointer"} as const;
const danger={minHeight:44,border:"1px solid rgba(255,120,120,.35)",borderRadius:12,background:"rgba(255,90,90,.08)",color:"#ffc4c4",padding:"0 14px",fontWeight:850,cursor:"pointer"} as const;
const dt={color:"#79908a",fontWeight:800} as const;const dd={margin:0,color:"#dce8e4"} as const;
